name: jahadgaran_festival
description: This project includes every useful thing that i use in other flutter projects
version: 1.0.2+3
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  accordion: ^2.5.1
  api_service:
    path: ../../packages/api_service
  auto_route: ^5.0.4
  bloc: ^8.1.2
  carousel_slider: ^4.2.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  data_table_2: ^2.5.0
  database_service:
    path: ../../packages/database_service
  dio: ^5.1.2
  dropdown_button2: ^2.1.3
  equatable: ^2.0.5
  fan_carousel_image_slider: ^0.1.2
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_glow: ^0.3.0
  flutter_hooks: ^0.18.6
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  number_paginator:
    path: ../../packages/number_paginator
  persian_datetime_picker: ^2.6.0
  responsive_framework: ^1.0.0
  talker_bloc_logger: ^2.0.0
  talker_dio_logger: ^2.0.0
  talker_flutter: ^3.0.0+1
  universal_html: ^2.2.3
  url_launcher: ^6.1.11

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.4.4
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.0
  very_good_analysis: ^5.0.0+1

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: false
  image_path: 'assets/images/png/ic_launcher.png'
  web:
    generate: true
    image_path: 'assets/images/png/ic_launcher.png'

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/png/
    - assets/images/png/organizations/
    - assets/images/png/rules/
    - assets/images/svg/

  fonts:
    - family: iranYekanWeb
      fonts:
        - asset: assets/fonts/Iranyekan thin.ttf
          weight: 200
        - asset: assets/fonts/Iranyekan light.ttf
          weight: 300
        - asset: assets/fonts/Iranyekan.ttf
          weight: 400
        - asset: assets/fonts/Iranyekan medium.ttf
          weight: 500
        - asset: assets/fonts/Iranyekan bold.ttf
          weight: 700
        - asset: assets/fonts/Iranyekan black.ttf
          weight: 800
