name: jahadgaran_festival
description: This project includes every useful thing that i use in other flutter projects
version: 1.0.1+2
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  accordion: ^2.5.1
  api_service:
    path: ../../packages/api_service
  appinio_video_player: ^1.2.0
  auto_route: ^5.0.4
  bloc: ^8.1.0
  carousel_slider: ^4.2.1
  crypto: ^3.0.2
  dartz: ^0.10.1
  database_service:
    path: ../../packages/database_service
  dio: ^5.1.1
  dropdown_button2: ^2.1.0
  equatable: ^2.0.5
  fan_carousel_image_slider: ^0.1.2
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_glow: ^0.3.0
  flutter_hooks: ^0.18.5+1
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.0+1
  fluttertoast: ^8.2.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  number_paginator:
    path: ../../packages/number_paginator
  persian_datetime_picker: ^2.5.0
  responsive_framework: ^0.2.0
  talker_dio_logger: ^1.0.2
  talker_flutter: ^2.2.1
  universal_html: ^2.2.1
  url_launcher: ^6.1.7

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.6.1
  very_good_analysis: ^3.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: 'assets/images/png/ic_launcher.png'
  web:
    generate: true
    image_path: 'assets/images/png/ic_launcher.png'

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/png/
    - assets/images/png/organizations/
    - assets/images/png/rules/
    - assets/images/svg/

  fonts:
    - family: iranYekanWeb
      fonts:
        - asset: assets/fonts/Iranyekan thin.ttf
          weight: 200
        - asset: assets/fonts/Iranyekan light.ttf
          weight: 300
        - asset: assets/fonts/Iranyekan.ttf
          weight: 400
        - asset: assets/fonts/Iranyekan medium.ttf
          weight: 500
        - asset: assets/fonts/Iranyekan bold.ttf
          weight: 700
        - asset: assets/fonts/Iranyekan black.ttf
          weight: 800
